---
abstract: 'HTTP Request Limitation for Plack apps'
author:
  - 'Koichi Taniguchi (a.k.a. nipotan) <taniguchi@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-LimitRequest
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  Plack::Middleware: 0
  Plack::Util::Accessor: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/nipotan/Plack-Middleware-LimitRequest
version: '0.02'
